// comment-draft.js — Persona E (cp-j0gw.5)
// Generates a DRAFT comment outline (markdown) from an institution analysis.
// SCAFFOLD ONLY — does not write substantive arguments. Reader fills [...] blocks.

const form = document.getElementById('comment-form');
const statusLine = document.getElementById('status-line');
const outlineRegion = document.getElementById('outline-region');
const outlinePre = document.getElementById('outline-pre');
const copyBtn = document.getElementById('copy-button');
const downloadBtn = document.getElementById('download-button');

function setStatus(msg, isError = false) {
  if (!statusLine) return;
  statusLine.textContent = msg;
  statusLine.classList.toggle('status-error', isError);
}

function pct(x) {
  if (typeof x !== 'number' || Number.isNaN(x)) return '—';
  return `${(x * 100).toFixed(2)}%`;
}

function money(x) {
  if (typeof x !== 'number' || Number.isNaN(x)) return '—';
  return `$${x.toLocaleString('en-US', { maximumFractionDigits: 0 })}`;
}

function buildOutline(result) {
  const today = new Date().toISOString().split('T')[0];
  const failing = result.programs.filter((p) => p.verdict === 'FAIL');
  const noiseBand = result.programs.filter((p) => p.noise_band && p.noise_band.fired);
  const notMeasured = result.programs.filter((p) => p.verdict === 'NOT MEASURED');

  const lines = [];
  lines.push(`# Public Comment Outline — DRAFT`);
  lines.push(``);
  lines.push(`**Subject:** Comment on the proposed STATS / Earnings-Premium rule (Federal Register 2026-07666)`);
  lines.push(`**Submitted by:** [your name and affiliation]`);
  lines.push(`**Date:** ${today}`);
  lines.push(`**Institution context:** ${result.instnm} (UNITID ${result.unitid}, ${result.stabbr})`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);
  lines.push(`> **Reader notice.** This outline was generated by the public CSU Deans EP Tool`);
  lines.push(`> (https://github.com/AJBcoding/csu-deans-ep-tool). The tool is built by`);
  lines.push(`> educators, not attorneys or legislative analysts. Every finding below is a`);
  lines.push(`> forward simulation on AHEAD's PPD:2026 negotiator analytic file. The first`);
  lines.push(`> official STATS earnings-premium release is scheduled for 2027-07-01.`);
  lines.push(`> Independently verify every citation against the primary sources before`);
  lines.push(`> filing this comment.`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  lines.push(`## 1. Findings at this institution`);
  lines.push(``);
  if (failing.length > 0) {
    lines.push(`### Programs failing the EP test`);
    lines.push(``);
    for (const p of failing) {
      lines.push(`- **${p.cip4_title}** (CIP ${p.cip4} · ${p.credlev}) — verdict: **FAIL** at ${pct(p.ep_gap_pct)} (cohort n=${p.cohort_count ?? '—'}; median earnings ${money(p.median_earn_p4)} vs benchmark ${money(p.benchmark)} via ${p.benchmark_route}).`);
    }
    lines.push(``);
  } else {
    lines.push(`No programs at this institution surface a FAIL verdict in the simulation.`);
    lines.push(``);
  }

  if (noiseBand.length > 0) {
    lines.push(`### Programs in the noise band (verdict could read either way under privacy noise)`);
    lines.push(``);
    for (const p of noiseBand) {
      lines.push(`- **${p.cip4_title}** (CIP ${p.cip4} · ${p.credlev}) — current verdict ${p.verdict} at ${pct(p.ep_gap_pct)}; gap is within ±15% of zero.`);
    }
    lines.push(``);
  }

  if (notMeasured.length > 0) {
    lines.push(`### Programs not measured (cohort suppression, invisibility, or out-of-scope)`);
    lines.push(``);
    for (const p of notMeasured) {
      lines.push(`- **${p.cip4_title || '(unknown)'}** (CIP ${p.cip4} · ${p.credlev}) — reason: ${p.not_measured_reason ?? 'unspecified'}.`);
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(``);
  lines.push(`## 2. Mechanism context (citations to the proposed rule)`);
  lines.push(``);
  if (Array.isArray(result.panels)) {
    for (const panel of result.panels) {
      lines.push(`- **${panel.id}** — ${panel.header}`);
    }
  }
  lines.push(``);
  lines.push(`Trigger reason for each: see Mechanism Library at /learn/. The full text of each panel — including the primary-source citations — appears in the tool's content/mdocs/ directory.`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  lines.push(`## 3. Suggested topics for substantive comment (you fill in)`);
  lines.push(``);
  lines.push(`The tool does not write substantive comment text. The headers below are`);
  lines.push(`scaffolds for the topics this institution's findings tend to surface.`);
  lines.push(`Each is a placeholder — write your own substantive position.`);
  lines.push(``);
  lines.push(`### 3.1 What this institution loses if the rule takes effect as written`);
  lines.push(``);
  lines.push(`[Describe the program-level and student-level impact in your own words.`);
  lines.push(`Reference the failing programs above; explain who they serve, what they`);
  lines.push(`teach, and why earnings-premium is or is not the right outcome metric for`);
  lines.push(`those programs at this institution.]`);
  lines.push(``);

  if (failing.length > 0) {
    lines.push(`### 3.2 The institution-level § 668.16(t) escalation pathway`);
    lines.push(``);
    lines.push(`[The Mechanism Library panel M18 walks through the five legal frames the`);
    lines.push(`Department's design must answer (Loper Bright + major-questions, OIRA`);
    lines.push(`Circular A-4 § 1, § 6, § E, and Motor Vehicle Mfrs. v. State Farm). If`);
    lines.push(`you have a legal position on the institution-level escalation design, this`);
    lines.push(`is where to put it. The tool does not take a legal position; it surfaces`);
    lines.push(`the questions for you to answer or to ask counsel about.]`);
    lines.push(``);
  }

  lines.push(`### 3.3 Cohort-floor methodology (cp-wssr finding)`);
  lines.push(``);
  lines.push(`[The OBBBA § 84001(c)(2)(A) statutory floor is 30 graduates; AHEAD's`);
  lines.push(`single-window count_wne_p4 may show fewer at this institution. Mechanism`);
  lines.push(`Library panel M01 walks through the AHEAD-published-flag override the tool`);
  lines.push(`applies. If your institution has cells in the 16-30 single-window range`);
  lines.push(`with PPD-published flags, you may want to address how the cohort-floor`);
  lines.push(`mismatch interacts with appeal scope under proposed § 668.603.]`);
  lines.push(``);

  lines.push(`### 3.4 Disparate impact on named populations`);
  lines.push(``);
  lines.push(`[Mechanism Library panel M14 covers RIA Table 3.19 named-population`);
  lines.push(`elevation. If this institution serves named populations (HBCU, MSI, HSI,`);
  lines.push(`AANAPISI, or programs in CIP 50.05/50.07/50.09/51.15) and the rule's`);
  lines.push(`elevation factor differs from the prose summary in the RIA, this is where`);
  lines.push(`to address it.]`);
  lines.push(``);

  lines.push(`---`);
  lines.push(``);
  lines.push(`## 4. Verification recipes — how each number above can be reproduced`);
  lines.push(``);
  if (failing.length > 0) {
    lines.push(`Each failing program above can be reproduced WITHOUT this tool, using only`);
    lines.push(`the AHEAD codebook + the Department's published file. Recipes:`);
    lines.push(``);
    for (const p of failing) {
      const r = p.verification_recipe;
      if (!r) continue;
      lines.push(`### ${p.cip4_title} (CIP ${p.cip4} · ${p.credlev})`);
      lines.push(``);
      lines.push(`- **Source data:** ${r.source_data}`);
      lines.push(`- **Source grain:** ${r.source_grain}`);
      lines.push(`- **Engine reference:** \`${r.engine_reference}\``);
      lines.push(`- **Source fields:** ${r.source_fields.join('; ')}`);
      lines.push(`- **Steps:**`);
      for (const step of r.steps) {
        lines.push(`  1. ${step}`);
      }
      lines.push(``);
    }
  }

  lines.push(`---`);
  lines.push(``);
  lines.push(`## 5. References`);
  lines.push(``);
  lines.push(`### Primary sources cited above`);
  lines.push(``);
  lines.push(`- AHEAD PPD:2026 — Program Performance Data file 112908 (Department of Education / NCES)`);
  lines.push(`- IPEDS Completions Survey (NCES)`);
  lines.push(`- OBBBA — Public Law 119-21, § 84001 (program-level EP test); § 81001 (graduate loan caps)`);
  lines.push(`- Higher Education Act § 498 (administrative-capability authority)`);
  lines.push(`- STATS NPRM — Federal Register 2026-07666 (proposed § 668.2(b), § 668.16(t), § 668.402(c)(3), § 668.403(d)(1), § 668.404(d), § 668.43(d)(1), § 668.603; RIA Tables 3.1, 3.9, 3.19)`);
  lines.push(`- OIRA Circular A-4 (2003) — § 1 problem statement; § 6 alternatives; § E uncertainty`);
  lines.push(`- *Loper Bright Enterprises v. Raimondo*, 603 U.S. ___ (2024)`);
  lines.push(`- *Motor Vehicle Mfrs. Ass'n v. State Farm Mut. Auto. Ins. Co.*, 463 U.S. 29 (1983)`);
  lines.push(``);
  lines.push(`### Tool reference`);
  lines.push(``);
  lines.push(`- This outline generated by the CSU Deans EP Tool — https://github.com/AJBcoding/csu-deans-ep-tool (MIT license).`);
  lines.push(`- Public Sources page: /sources.html.`);
  lines.push(`- Mechanism Library: /learn/.`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);
  lines.push(`**End of DRAFT outline.** Edit substantively before filing. Verify every citation against the primary source. The tool is not a legal product, not legal advice, and not a filed position of any institution.`);
  lines.push(``);

  return lines.join('\n');
}

async function fetchAnalysis(unitid) {
  const res = await fetch(`/api/v1/analysis/${unitid}`);
  if (!res.ok) {
    throw new Error(`API ${res.status}`);
  }
  return await res.json();
}

let lastOutline = '';
let lastUnitid = '';

if (form && outlineRegion && outlinePre) {
  form.addEventListener('submit', async (ev) => {
    ev.preventDefault();
    const data = new FormData(form);
    const unitid = String(data.get('unitid') ?? '').trim();
    if (!/^[0-9]+$/.test(unitid)) {
      setStatus('UNITID must be all digits.', true);
      return;
    }
    setStatus(`Fetching analysis for UNITID ${unitid}…`);
    outlineRegion.hidden = true;
    try {
      const result = await fetchAnalysis(unitid);
      lastOutline = buildOutline(result);
      lastUnitid = unitid;
      outlinePre.textContent = lastOutline;
      outlineRegion.hidden = false;
      setStatus(`Outline generated for ${result.instnm} (${result.unitid}). Edit and verify before filing.`);
    } catch (err) {
      setStatus(`Could not fetch analysis: ${String(err)}`, true);
    }
  });
}

if (copyBtn) {
  copyBtn.addEventListener('click', async () => {
    if (!lastOutline) return;
    try {
      await navigator.clipboard.writeText(lastOutline);
      setStatus('Outline copied to clipboard.');
    } catch (e) {
      setStatus('Copy failed; select-all the text below instead.', true);
    }
  });
}

if (downloadBtn) {
  downloadBtn.addEventListener('click', () => {
    if (!lastOutline) return;
    const blob = new Blob([lastOutline], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `comment-outline-${lastUnitid}.md`;
    a.click();
    URL.revokeObjectURL(url);
  });
}
